apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: helm-keda
spec:
  package: ghcr.io/hops-ops/helm-keda:{{ .Values.version }}
{{- if .Values.skipDependencyResolution }}
  skipDependencyResolution: true
{{- end }}
{{- if .Values.skipDependencyResolution }}
---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: hops-ops-helm-kedarender
spec:
  package: ghcr.io/hops-ops/helm-kedarender:{{ .Values.version }}
{{- end }}
